### ISSUE TITLE
Stabilize API

### ISSUE THREAD

**Issue by erik** [erik/translate#1]
URL endpoints for the API need to be finalized, any changes to the format of the data returned should be finished. 
- Should URLs be versioned or no? 
  - Opinion seems to be split on this. Could stick with `/api/v1/method`, do something like `/api/method` and make changes backward compatible, do `/api/method` and specify version via `accept/content-type` HTTP headers.
  - This doesn't have to be written in stone, since there isn't even a client lib yet, but should pick one and stick with it.

**Comment by lionaneesh** [comment]
I suggest we should add versioning in our api.
- We can't plan for the unseen future.
- Backward compatibility will become more of a liability in future.
- Some of the most successful APIs use versioning. Ex: Google, Linkedin, Dropbox, Foursquare, Twitter etc.

I suggest we add versioning in urls, something like `/api/v1/method` , because I find them simpler.

**Comment by erik** [comment]
I would definitely agree with you on that. 

While the `Accept: api-v2` /  `Content-type: application/api-v2+json` or whatever other solution would leave cleaner URLs, it would be a lot less immediately obvious for developers all around.

Guess I'll stick with the `/api/v1/method` path I'm currently using then.

**Comment by erik** [comment]
Documented API in e1ae4bc579.
